In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.array([
    [95, 91],
    [92, 93],
    [98, 97],
    [100, 97]
])

array([[ 95,  91],
       [ 92,  93],
       [ 98,  97],
       [100,  97]])

In [4]:
arr2d = np.array([
    [95, 91],
    [92, 93],
    [98, 97],
    [100, 97]
])

In [6]:
arr2d.ndim

2

In [7]:
arr2d.shape

(4, 2)

In [9]:
arr2d.size

8

In [10]:
arr2d.dtype

dtype('int32')

In [11]:
pd.DataFrame(data=arr2d, columns=['A반', 'B반'])

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97

In [12]:
df1 = pd.DataFrame(data=arr2d, columns=['A반', 'B반'])

In [16]:
df1.iloc[0]

A반    95
B반    91
Name: 0, dtype: int32

In [18]:
df1['A반']

0     95
1     92
2     98
3    100
Name: A반, dtype: int32

In [19]:
arr2d_2 = np.array([
    [87, 85],
    [89, 90]

])

In [20]:
arr2d_2

array([[87, 85],
       [89, 90]])

In [21]:
df2 = pd.DataFrame(data=arr2d_2, columns=['A반', 'B반'])

In [22]:
df2

A반  B반
0  87  85
1  89  90

In [25]:
arr2d_4 = np.array([
    [100],
    [100],
    [100],
    [100]
])

In [26]:
arr2d_4

array([[100],
       [100],
       [100],
       [100]])

In [27]:
df4 = pd.DataFrame(data=arr2d_4, columns=['D반'])

In [28]:
df4

D반
0  100
1  100
2  100
3  100

In [29]:
df1.join(df4)

A반  B반   D반
0   95  91  100
1   92  93  100
2   98  97  100
3  100  97  100

In [31]:
df2

A반  B반
0  87  85
1  89  90

In [33]:
pd.concat([df1, df2], ignore_index=True)

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97
4   87  85
5   89  90

In [34]:
df1_df2 = pd.concat([df1, df2], ignore_index=True)

In [35]:
df1_df2

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97
4   87  85
5   89  90

In [36]:
# 표를 만드는 일반적인 방법1

In [37]:
data1 = {'id': ['hong1', 'hong2', 'hong3', 'hong4', 'hong5'],
         '이름': ['홍일동', '홍이동', '홍삼동', '홍사동', '홍오동'],
         '키': [166,	168,	170,	172,	174]
         }

In [38]:
pd.DataFrame(data1)

id   이름    키
0  hong1  홍일동  166
1  hong2  홍이동  168
2  hong3  홍삼동  170
3  hong4  홍사동  172
4  hong5  홍오동  174

In [54]:
df1_stu.columns

Index(['이름', '키'], dtype='object')

In [55]:
df1_stu['이름']

id
hong1    홍일동
hong2    홍이동
hong3    홍삼동
hong4    홍사동
hong5    홍오동
Name: 이름, dtype: object

In [47]:
df1_stu = pd.DataFrame(data1)

In [48]:
df1_stu.index

RangeIndex(start=0, stop=5, step=1)

In [50]:
df1_stu.set_index('id', inplace=True)

In [51]:
df1_stu

이름    키
id             
hong1  홍일동  166
hong2  홍이동  168
hong3  홍삼동  170
hong4  홍사동  172
hong5  홍오동  174

In [52]:
df1_stu.index

Index(['hong1', 'hong2', 'hong3', 'hong4', 'hong5'], dtype='object', name='id')

In [56]:
df1_stu.index.name

'id'

In [53]:
df1_stu.loc['hong3']

이름    홍삼동
키     170
Name: hong3, dtype: object

In [ ]:
# 표를 만드는 일반적인 방법2

In [43]:
idx = ['hong1', 'hong2', 'hong3', 'hong4', 'hong5']

In [40]:
data2 = {
    '이름': ['홍일동', '홍이동', '홍삼동', '홍사동', '홍오동'],
    '키': [166,	168,	170,	172,	174]
}

In [44]:
pd.DataFrame(data2, index=pd.Index((idx), name='student'))

이름    키
student          
hong1    홍일동  166
hong2    홍이동  168
hong3    홍삼동  170
hong4    홍사동  172
hong5    홍오동  174

In [45]:
df_stu = pd.DataFrame(data2, index=pd.Index((idx), name='student'))

In [49]:
df_stu.index

Index(['hong1', 'hong2', 'hong3', 'hong4', 'hong5'], dtype='object', name='student')

In [46]:
df_stu.loc['hong4']

이름    홍사동
키     172
Name: hong4, dtype: object

In [57]:
df1 = pd.DataFrame({'Name': ['Harry Potter',	'David Baker',	'John Smith',	'Juan Martinez',	'Jane Connor'],
                    'Gender': ['Male',	'Male',	'Male',	'Male',	'Female'],
                    'Age': [23, 31, 22, 36, 30]
                    })

In [58]:
df1

Name  Gender  Age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Juan Martinez    Male   36
4    Jane Connor  Female   30

In [59]:
df2 = pd.DataFrame({'Name': ['John Smith',	'Alex Du Bois',	'Joanne Rowling',	'Jane Connor'],
                    'Position': ['Intern',	'Team Lead',	'Manager',	'Manager'],
                    'Wage': [25000, 75000, 90000, 70000]
                    })

In [60]:
df2

Name   Position   Wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Connor    Manager  70000

In [66]:
df1.merge(df2, on='Name', how='inner')

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [61]:
df1.merge(df2, on='Name')

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [62]:
df1.merge(df2)

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [63]:
df1.merge(df2, on='Name', how='left')

Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  Female   30  Manager  70000.0

In [64]:
df1.merge(df2, on='Name', how='right')

Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  Female  30.0    Manager  70000

In [65]:
df1.merge(df2, on='Name', how='outer')

Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  Female  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN

In [67]:
# 엑셀에서 데이터 가져오기

In [68]:
pd.read_excel('C:/ex/data/test.xlsx')

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [69]:
pd.read_excel('C:/ex/data/stu_score.xlsx')

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [70]:
pd.read_excel('C:/ex/data/stu_score.xlsx', sheet_name='2학기')

학생   국   영   수
0  A  80  90  50
1  B  90  95  50
2  C  95  70  50
3  D  70  85  50
4  E  75  90  50

In [71]:
df_stu_score_1 = pd.read_excel('C:/ex/data/stu_score.xlsx', sheet_name='1학기')

In [72]:
df_stu_score_1.head()

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [73]:
df_stu_score_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학생      5 non-null      object
 1   국       5 non-null      int64 
 2   영       5 non-null      int64 
 3   수       5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes


In [74]:
df_stu_score_1.describe()

국          영          수
count   5.000000   5.000000   5.000000
mean   82.000000  86.000000  84.000000
std    10.368221   9.617692   7.416198
min    70.000000  70.000000  75.000000
25%    75.000000  85.000000  80.000000
50%    80.000000  90.000000  85.000000
75%    90.000000  90.000000  85.000000
max    95.000000  95.000000  95.000000

In [82]:
df_stu_score_1.index

RangeIndex(start=0, stop=5, step=1)

In [84]:
df_stu_score_1_idx = df_stu_score_1.set_index('학생')

In [85]:
df_stu_score_1_idx

국   영   수
학생            
A   80  90  85
B   90  95  95
C   95  70  75
D   70  85  80
E   75  90  85

In [86]:
df_stu_score_1_idx.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object', name='학생')

In [87]:
df_stu_score_1_idx.loc['A']

국    80
영    90
수    85
Name: A, dtype: int64

In [91]:
print("%.2f" % df_stu_score_1_idx.loc['A'].mean())
print("%.2f" % df_stu_score_1_idx.loc['B'].mean())
print("%.2f" % df_stu_score_1_idx.loc['C'].mean())
print("%.2f" % df_stu_score_1_idx.loc['D'].mean())
print("%.2f" % df_stu_score_1_idx.loc['E'].mean())

85.00
93.33
80.00
78.33
83.33


In [92]:
df_stu_score_1.values

array([['A', 80, 90, 85],
       ['B', 90, 95, 95],
       ['C', 95, 70, 75],
       ['D', 70, 85, 80],
       ['E', 75, 90, 85]], dtype=object)

In [96]:
df_stu_score_1

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [97]:
df_stu_score_1_drop = df_stu_score_1.drop('학생', axis=1)

In [98]:
df_stu_score_1_drop

국   영   수
0  80  90  85
1  90  95  95
2  95  70  75
3  70  85  80
4  75  90  85

In [99]:
df_stu_score_1_drop.values

array([[80, 90, 85],
       [90, 95, 95],
       [95, 70, 75],
       [70, 85, 80],
       [75, 90, 85]], dtype=int64)

In [100]:
df_stu_score_1_drop.values.mean()

84.0

In [103]:
df_stu_score_1.sort_values(by='국', ascending=False)

학생   국   영   수
2  C  95  70  75
1  B  90  95  95
0  A  80  90  85
4  E  75  90  85
3  D  70  85  80

In [108]:
stu_mean = [df_stu_score_1_idx.loc['A'].mean(), df_stu_score_1_idx.loc['B'].mean(), df_stu_score_1_idx.loc['C'].mean(),
            df_stu_score_1_idx.loc['D'].mean(), df_stu_score_1_idx.loc['E'].mean()]

In [110]:
df_stu_score_1['stu_mean'] = stu_mean

In [111]:
df_stu_score_1

학생   국   영   수   stu_mean
0  A  80  90  85  85.000000
1  B  90  95  95  93.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333
4  E  75  90  85  83.333333

In [112]:
df_stu_score_1.sort_values(by='stu_mean', ascending=False)

학생   국   영   수   stu_mean
1  B  90  95  95  93.333333
0  A  80  90  85  85.000000
4  E  75  90  85  83.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333

In [2]:
import pandas as pd

# 집계 : aggregation 
# mean

In [ ]:
# help(pd.pivot_table)
# Help on function pivot_table in module pandas.core.reshape.pivot:

# pivot_table(data: 'DataFrame', values=None, index=None, columns=None, aggfunc: 'AggFuncType' = 'mean', fill_value=None, margins: 'bool' = False, dropna: 'bool' = True, margins_name: 'Hashable' = 'All', observed: 'bool | lib.NoDefault' = <no_default>, sort: 'bool' = True) -> 'DataFrame'
#     Create a spreadsheet-style pivot table as a DataFrame.

#     The levels in the pivot table will be stored in MultiIndex objects
#     (hierarchical indexes) on the 