In [23]:
import tensorflow as tf

In [24]:
tf.__version__

'2.13.0'

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
import pandas as pd

In [27]:
df_ori = pd.read_csv('./data/sonar3.csv',header=None)
df = df_ori

In [28]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   0  
1  0.0052  0.0044   0  
2  0.0095  0.0078   0  
3  0.0040  0.0117   0  
4  0.0107  0.0094   0  

[5 rows x 61 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [30]:
df[60].value_counts()

60
1    111
0     97
Name: count, dtype: int64

In [31]:
X = df.iloc[:, :60].values
y = df.iloc[:, 60].values

In [32]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [33]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
# 기본값 훈련셋, 테스트셋
# train_test_split ---> HoldOut 
# 0.75 : 0.25 비율이 기본값이다. (*100 퍼센트)
# 섞여서 나온다.

In [36]:
train_test_split(X, y, test_size=0.3, shuffle=True)

[array([[0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
        [0.0084, 0.0153, 0.0291, ..., 0.0031, 0.0072, 0.0045],
        [0.0264, 0.0071, 0.0342, ..., 0.0077, 0.0078, 0.0066],
        ...,
        [0.0721, 0.1574, 0.1112, ..., 0.0147, 0.0157, 0.0129],
        [0.0095, 0.0308, 0.0539, ..., 0.003 , 0.0031, 0.0033],
        [0.0228, 0.0106, 0.013 , ..., 0.0045, 0.0063, 0.0039]]),
 array([[0.0228, 0.0853, 0.1   , ..., 0.0093, 0.0012, 0.0036],
        [0.0119, 0.0582, 0.0623, ..., 0.0073, 0.003 , 0.0138],
        [0.0211, 0.0128, 0.0015, ..., 0.0039, 0.0051, 0.0015],
        ...,
        [0.0442, 0.0477, 0.0049, ..., 0.0105, 0.0059, 0.0105],
        [0.005 , 0.0017, 0.027 , ..., 0.0063, 0.0017, 0.0028],
        [0.0197, 0.0394, 0.0384, ..., 0.0045, 0.0047, 0.0054]]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1

In [37]:
208* 0.7

145.6

In [38]:
X_train , X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3, shuffle=True)

In [39]:
X_train.shape

(145, 60)

In [40]:
X_test.shape

(63, 60)

In [41]:
y_train.shape

(145,)

In [42]:
y_test.shape

(63,)

In [43]:
# 학습용, 테스트용
# X_train , X_test, 
# y_train , y_test

In [44]:
model = Sequential()
model.add( Dense(24, 
                input_dim=60,
                activation='relu'
))
model.add( Dense(10, activation='relu'))
model.add( Dense(1, activation='sigmoid'))

model.compile( 
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit( X_train, y_train,
                    epochs=200, batch_size=10 )

Epoch 1/200
15/15 [==============================] - 0s 1ms/step - loss: 0.7040 - accuracy: 0.4414
Epoch 2/200
15/15 [==============================] - 0s 929us/step - loss: 0.6837 - accuracy: 0.5793
Epoch 3/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6775 - accuracy: 0.5724
Epoch 4/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6699 - accuracy: 0.5586
Epoch 5/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6663 - accuracy: 0.5655
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6601 - accuracy: 0.5655
Epoch 7/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6537 - accuracy: 0.6069
Epoch 8/200
15/15 [==============================] - 0s 929us/step - loss: 0.6465 - accuracy: 0.6759
Epoch 9/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6393 - accuracy: 0.6483
Epoch 10/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6286 - accuracy: 0.6690
Epoch

In [45]:
model = Sequential()
model.add( Dense(24, 
                input_dim=60,
                activation='relu'
))
model.add( Dense(10, activation='relu'))
model.add( Dense(1, activation='sigmoid'))

model.compile( 
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit( X_test, y_test,
                    epochs=200, batch_size=10 )

Epoch 1/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6917 - accuracy: 0.4286
Epoch 2/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6795 - accuracy: 0.5714
Epoch 3/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6708 - accuracy: 0.6190
Epoch 4/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6603 - accuracy: 0.6032
Epoch 5/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6464 - accuracy: 0.7143
Epoch 6/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6361 - accuracy: 0.7143
Epoch 7/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6293 - accuracy: 0.7143
Epoch 8/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6173 - accuracy: 0.7302
Epoch 9/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6112 - accuracy: 0.7302
Epoch 10/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6058 - accuracy: 0.7302
Epoch 11/200
7/7 [===========

In [46]:
# 실제 모델 정확도는?? 테스트용으로 확인 해라. 
# model.evaluate( x=None,  
#     y=None,  
#     batch_size=None,  
#     verbose='auto',  
#     sample_weight=None,  
#     steps=None,  
#     callbacks=None,  
#     max_queue_size=10,  
#     workers=1,  
#     use_multiprocessing=False,  
#     return_dict=False,  
#     **kwargs,  )
model.evaluate( X_test, y_test )

2/2 [==============================] - 0s 3ms/step - loss: 0.0717 - accuracy: 1.0000


[0.07171808183193207, 1.0]

In [47]:
score = model.evaluate( X_test, y_test )

2/2 [==============================] - 0s 4ms/step - loss: 0.0717 - accuracy: 1.0000


In [48]:
score

[0.07171808183193207, 1.0]

In [49]:
score[1]

1.0

In [50]:
# test셋에서의 정확도를 가지고 판단해야 한다. 100% 정확도를 얻음


In [51]:
model.save('./model/myfirst_model.hdf5')

c:\anaconda3\envs\mldltest1\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
