In [12]:
# Number of Attributes: 
#   9 including the class attribute

# Attribute Information:
#   mpg: continuous
#   cylinders: multi-valued discrete
#   displacement: continuous
#   horsepower 마력: continuous
#   weight 중량 : continuous
#   acceleration:  continuous
#   model year 차량 생산국: multi-valued discrete
#   origin 제조국가: multi-valued discrete
#   car name 이름: string (unique for each instance)

# Missing Attribute Values: 
#   horsepower has 6 missing values

import pandas as pd
import math 
import numpy as np
import seaborn as sns

In [6]:
mpg_ori = pd.read_csv("C:/shjung/pythonExam/240812_machineLearning/autompg_copy.csv", encoding="cp949")
 

In [7]:
mpg_ori.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [8]:
mpg_ori.horsepower.dtype

dtype('O')

In [15]:
mpg_ori.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', nan, '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [11]:
mpg_df = mpg_ori

In [14]:
mpg_df.horsepower.replace('?', np.nan, inplace=True)

In [16]:
mpg_df.horsepower.astype('float')

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [18]:
mpg_df.horsepower = mpg_df.horsepower.astype('float')

In [19]:
mpg_df.horsepower

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [20]:
help(np.histogram)

Help on _ArrayFunctionDispatcher in module numpy:

histogram(a, bins=10, range=None, density=None, weights=None)
    Compute the histogram of a dataset.

    Parameters
    ----------
    a : array_like
        Input data. The histogram is computed over the flattened array.
    bins : int or sequence of scalars or str, optional
        If `bins` is an int, it defines the number of equal-width
        bins in the given range (10, by default). If `bins` is a
        sequence, it defines a monotonically increasing array of bin edges,
        including the rightmost edge, allowing for non-uniform bin widths.

        .. versionadded:: 1.11.0

        If `bins` is a string, it defines the method used to calculate the
        optimal bin width, as defined by `histogram_bin_edges`.

    range : (float, float), optional
        The lower and upper range of the bins.  If not provided, range
        is simply ``(a.min(), a.max())``.  Values outside the range are
        ignored. The first elemen

In [22]:
mpg_df['horsepower'].dtype

dtype('float64')

In [23]:
mpg_df.horsepower.dtype

dtype('float64')

In [26]:
mpg_df['horsepower'].isna().sum()

6

In [27]:
mpg_df.dropna(subset=['horsepower'], axis=0, inplace=True)

In [28]:
mpg_df['horsepower'].isna().sum()

0

In [29]:
mpg_df['horsepower'].shape

(392,)

In [30]:
np.histogram(mpg_df['horsepower'], bins=3)

(array([257, 103,  32], dtype=int64),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [31]:
count, bin_dividers = np.histogram(mpg_df['horsepower'], bins=3)

In [33]:
bin_names= ['저출력', '보통출력', '고출력']

In [35]:
help(pd.cut)

Help on function cut in module pandas.core.reshape.tile:

cut(x, bins, right: 'bool' = True, labels=None, retbins: 'bool' = False, precision: 'int' = 3, include_lowest: 'bool' = False, duplicates: 'str' = 'raise', ordered: 'bool' = True)
    Bin values into discrete intervals.

    Use `cut` when you need to segment and sort data values into bins. This
    function is also useful for going from a continuous variable to a
    categorical variable. For example, `cut` could convert ages to groups of
    age ranges. Supports binning into an equal number of bins, or a
    pre-specified array of bins.

    Parameters
    ----------
    x : array-like
        The input array to be binned. Must be 1-dimensional.
    bins : int, sequence of scalars, or IntervalIndex
        The criteria to bin by.

        * int : Defines the number of equal-width bins in the range of `x`. The
          range of `x` is extended by .1% on each side to include the minimum
          and maximum values of `x`.
    

In [37]:
mpg_df['hp_bin'] = pd.cut(x=mpg_df['horsepower'], bins=bin_dividers, labels=bin_names, include_lowest=True)

In [39]:
# 원핫 인코딩 해주는 함수
pd.get_dummies(mpg_df['hp_bin'])

저출력   보통출력    고출력
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
393   True  False  False
394   True  False  False
395   True  False  False
396   True  False  False
397   True  False  False

[392 rows x 3 columns]

In [40]:
arr = np.array(['남','남','남','여','여'])

In [41]:
pd.get_dummies(arr)

남      여
0   True  False
1   True  False
2   True  False
3  False   True
4  False   True

## 정규화 Normalization

### 1) 최소-최대 정규화

In [2]:
# scikit-learn 개념

from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]



scaler = MinMaxScaler()
#학습 scaler.fit()




In [5]:
print(scaler.fit(data))
scaler.fit(data)


MinMaxScaler()


MinMaxScaler()

In [6]:
scaler.transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [7]:
MinMaxScaler()

print(scaler.data_max_)
# [ 1. 18.]
print(scaler.transform(data))
# [[0.   0.  ]
#  [0.25 0.25]
#  [0.5  0.5 ]
#  [1.   1.  ]]
print(scaler.transform([[2, 2]]))
# [[1.5 0. ]]


[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[[1.5 0. ]]
