<a href="https://colab.research.google.com/github/raki77/pythonExam/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%EA%B8%B0%EC%B4%88_%EC%BD%94%EB%9E%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy

In [6]:
import numpy as np

In [9]:
# array(...)
#     array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
#           like=None)
#     Create an array.

help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [7]:
!pwd

/content


In [4]:
!find / -name 'numpy*'

/usr/include/boost/python/numpy
/usr/include/boost/python/numpy/numpy_object_mgr_traits.hpp
/usr/include/boost/python/numpy.hpp
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/include/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/_virtual_includes/pybind11/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy/numpyconfig.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tensorflow/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/dtensor/python/numpy_util.py
/usr/local/lib/python3.10/dist-packages/tensorflow/d

In [ ]:
# !pip install 패키지명

In [10]:
# np.array(1,2,3) #error

arr1 = np.array([1,2,3])
type(arr1)

# numpy.ndarray : n차원 배열
# nd : dimension (차원)
# 머신러닝 : 차원축소



numpy.ndarray

In [11]:
arr1.shape

(3,)

In [20]:
arr1.size

6

In [21]:
arr1.ndim

2

In [15]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
arr2.shape

(2, 3)

In [16]:
arr2.size

6

In [18]:
arr2.transpose

<function ndarray.transpose>

In [22]:
arr2.ndim

2

In [24]:
arr3 = np.array([[[1,2,3],
                 [4,5,6]],
                  [[1,2,3],
                 [4,5,6]]])

In [26]:
arr3.size

12

In [27]:
arr3.shape

(2, 2, 3)

In [28]:
arr4 = np.array(
                [[1],
                [2],
                [-1.0],
                [3.14]]
                )

In [31]:
arr4.shape

(4, 1)

In [33]:
arr4.ndim

2

In [36]:
arr5 = np.array([[[[1,2,-1,3.14]]]])


In [38]:
arr5.ndim

4

In [40]:
arr5.shape

(1, 1, 1, 4)

In [41]:
mu = np.array([1,2,3])

In [43]:
nu = np.array([4,4,4])

In [45]:
# 스칼라 한 개의 상수 개념, 벡터 여러개 개념
# 유니버셜 계산
2 * mu

array([2, 4, 6])

In [47]:
mu + nu

array([5, 6, 7])

In [49]:
# 스칼라 연산의 덧셈
2 * (mu + nu)

array([10, 12, 14])

In [55]:
# 행렬의 연산 (대문자)
A = np.array([[3,6],[4,5]])
A


array([[3, 6],
       [4, 5]])

In [57]:
B = np.array([[5,6],[7,8]])
A - B

array([[-2,  0],
       [-3, -3]])

In [77]:
C = np.array([[5,8,9],[6,7,3]])
A + C


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [84]:
D = np.array([[5,8,9],[6,7]])

A - D


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [65]:
np.all([True, True, True])

True

In [66]:
np.all([True, True, False])

False

In [67]:
np.any([False,False,False])

False

In [69]:
np.any([True,False,False])

True

In [86]:
A = np.array([[1,2,3],[4,5,6]])

In [87]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
A.transpose().transpose()

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [93]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
B = np.array([[3,4],[5,6]])
B.shape

(2, 2)

In [96]:
B.transpose()

array([[3, 5],
       [4, 6]])

In [101]:
A = np.array([[3,7],
             [2,4]])

In [103]:
B = np.array([[1,5],
             [3,2]])

A * B

array([[ 3, 35],
       [ 6,  8]])

In [108]:
print(3/1)
print(7/5)
print(2/3)
print(4/2)

A / B

3.0
1.4
0.6666666666666666
2.0


array([[3.        , 1.4       ],
       [0.66666667, 2.        ]])

In [109]:
A + B

array([[ 4, 12],
       [ 5,  6]])

In [110]:
B + A

array([[ 4, 12],
       [ 5,  6]])

In [112]:
A - B

array([[ 2,  2],
       [-1,  2]])

In [113]:
B - A

array([[-2, -2],
       [ 1, -2]])

In [115]:
B * A

array([[ 3, 35],
       [ 6,  8]])

In [117]:
B / A

array([[0.33333333, 0.71428571],
       [1.5       , 0.5       ]])

In [119]:
# 내적
# dot product
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

A.dot(B)

array([[ 58,  64],
       [139, 154]])

In [120]:
# 행렬의 내적 : dot product
Matrix_a = np.array([[1,1,2],
                     [2,1,1]])
Matrix_b = np.array([[1,1],
                    [2,1],
                    [1,3]])
Matrix_a.dot(Matrix_b)


array([[5, 8],
       [5, 6]])