In [2]:
import numpy as np 

str(np.array([2,3]))
arr_int = np.array([2,3])

In [3]:
np.arange(1, 6+1)

array([1, 2, 3, 4, 5, 6])

In [4]:

np.arange(1, 6+1).reshape((2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(1, 6+1).reshape((2,3)).reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [6]:
np.arange(1, 6+1).reshape((2,3)).reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [7]:
arr_2d = np.arange(1, 6+1).reshape((2,3))
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr_2d.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [10]:
np.array([[1,3,5]
          ,[2,4,6]])

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
np.array([[1,3,5]
        ,[2,4,6]]).reshape(6)

array([1, 3, 5, 2, 4, 6])

In [44]:

# 3 dim -> 2 dim -> 1 dim
res = np.array([
        [[1,3,5],[2,4,6]],
        [[7,8,9],[10,11,12]]
        ])
 
di2 = res.reshape(2,6)
print(di2.ndim , "ndim", di2.shape, di2)
di1 = di2.reshape(12)
print(di1.ndim , "ndim", di1.shape, di1)


di3 = np.arange(1, 12+1)
di4 = di3.reshape((1,4,3))
di5 = di4.reshape((2, 6))
di6 = di5.reshape((2, 2, 3))
di6

2 ndim (2, 6) [[ 1  3  5  2  4  6]
 [ 7  8  9 10 11 12]]
1 ndim (12,) [ 1  3  5  2  4  6  7  8  9 10 11 12]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
x1 = np.arange(1, 12+1)
x1.reshape((-1,12))
x1.reshape((2,6)) 
x1.reshape((1,4,3))
x1.reshape((2,6,-1))
x1.reshape((1,-1,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [49]:
x1.reshape((2,6,-1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])