In [1]:
import numpy as np

In [2]:
# Numpy 배열:
#     왜 배열 자료구조가 그런 빠른 연산을 가능하게 하는지를 이해하기 위해 먼저 자료구조별 메모리에 저장되는 방식을 알아야 한다.
#     일반적으로 대부분의 언어에서 배열(array)은 같은 자료형을 가진 자료들을 나열하여 메모리에 연속으로 저장하여 만든 자료들의 그룹이라고 언급되어진다.
#     그 안에 있는 각각의 값들은 배열의 요소라고 불리며, 배열의 요소를 간단히 구별하기 위해 사용하는 인덱스라는 번호를 사용하고 인덱스는 항상 0부터 시작한다. 대부분의 자료형은 배열로 구성이 가능하고 구성 형태에 따라 1차원 배열, 2차원 배열, 3차원 배열로 구성된다.
#     전에 자료구조는 자료를 효과적으로 저장하는 것에 가장 초점이 맞추어진 개념이라고 설명하였다. 이에 자료가 배열과 리스트에서 각각 어떻게 저장이 되는지를 알아보는 것이 배열의 장단점을 이해하고 배열을 사용하여야만 하는 이유를 명확하게 아는 방법이다.


In [3]:
arr1 = np.array([1,2,3])


In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr1[0]

1

In [8]:
# 어떨때는 데이타가 2대신 two같은 다른 형이 들어올 수 있다.
# 원칙은 다른 타입은 NO
arr1_1 = np.array([1, 'two', 3])


In [9]:
arr1_1

array(['1', 'two', '3'], dtype='<U11')

In [25]:
arr2= np.array([[1,2,3], [4,5,6]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 3)

In [28]:
arr3 = np.array([
                [[1,2,3], [4,5,6]],                
                [[1,2,3], [4,5,6]]
            ])

In [29]:
# demension
arr3.ndim

3

In [30]:
# 행렬 나타낸다.
arr3.shape

(2, 2, 3)

In [31]:
# Numpy 배열 :
    # 다차원 배열 객체, 다양한 파생 객체(행렬 등)를 포함한 배열에 대한 빠른 작업을 위한 일련의 루틴을 제공하는 Python 라이브러리다. 
    # 이산 푸리에 변환, 기본 선형 대수학, 기본 통계 연산, 무작위 시뮬레이션 등을 지원한다.
    # NumPy 패키지의 핵심은 ndarray 객체다. 이것은 동일한 데이터 타입의 n 차원의 배열을 위한 작업 처리를 한다


In [32]:
# [시퀀스]에서 [시간]이 들어가면 [시계열]이다,.

# NumPy 배열은 Python 리스트(동적으로 커질 수 있음)와 달리 생성 시 고정된 크기를 갖는다.
# ndarray의 크기를 변경하면 새 배열이 생성되고 원본이 삭제된다.
# NumPy 배열의 요소는 모두 동일한 데이터 유형이어야 하므로 메모리에서 동일한 크기가 된다.
# 리스트는 다양한 크기의 배열을 허용한다.

# NumPy 배열은 많은 수의 데이터에 대한 고급 수학 및 기타 유형의 연산을 용이하게 한다. 
# 일반적으로 이러한 작업은 Python의 내장 시퀀스를 사용하는 것보다 더 적은 코드로 훨씬 효율적으로 실행된다.
# 점점 더 많은 과학 및 수학 Python 기반 패키지가 NumPy 배열을 사용하고 있다. 이들은 일반적으로 Python 시퀀스 입력을 지원하지만 처리 전에 이러한 입력을 NumPy 배열로 변환하고 종종 NumPy 배열을 출력한다. 
# 다시 말해, 오늘날의 과학/수학 Python 기반 소프트웨어를 효율적으로 사용하려면 Python의 내장 시퀀스 유형을 사용하는 방법을 아는 것만으로는 충분하지 않다. NumPy 배열을 사용하는 방법도 반드시 알아야 한다.




In [33]:

# 벡터 : 통채로 계산, 

# 파이썬은 직접적으로 배열을 지원하지 않고, NumPy 라이브러리로 배열 자료 구조를 사용할 수 있게 하였다고 그 전에 배웠다.
# 그 전에 배운 일반적인 프로그래밍 언어에서의 배열 개념은 파이썬에서도 크게 다르지 않다. 
# 프로그래밍에서는 최대한 연산 횟수를 줄이는 것이 성능을 높이는 방법이다. 

# 대규모 연산에 있어서 반복문을 사용할 경우 매 반복 횟수마다 연산을 하므로 성능에 매우 안 좋은 영향을 끼친다. 
# NumPy 배열을 사용하면 반복문을 사용하지 않고 간결한 배열 연산을 사용해 많은 종류의 데이터 처리 작업을 할 수 있다. 
# 배열 연산을 사용해서 반복문을 명시적으로 제거하는 기법을 흔히 벡터화라고 하는데, 일반적으로 벡터화된 배열에 대한 산술 연산은 순수 파이썬 연산에 비해 2~3배에서 많게는 수십, 수백 배까지 빠르다. 

# 나중에 배우게 될 [브로드캐스팅]은 아주 강력한 [벡터 연산 방법]이다.


In [34]:
np.__version__

'1.26.4'

In [38]:
np.array((1,2,3))

array([1, 2, 3])

In [39]:
tmp=np.array({1,2,3})

In [40]:
# iterable
di2 = {'a': 'apple', 'b': 'banana'}

In [41]:
np.array(di2)

array({'a': 'apple', 'b': 'banana'}, dtype=object)

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1, 10+1, 3)

array([ 1,  4,  7, 10])

In [49]:
arr_test = np.array([1, 'a', True])

In [48]:
np.array([1, True])

array([1, 1])

In [50]:
type(arr_test[0])

numpy.str_

In [52]:
# default 50개, 1-10까지 선형 나누기
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [53]:
# 1000개 그림
np.linspace(1, 10, num= 1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

In [54]:
# 0을 10개 출력하라
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [62]:
arr3[1][1][1], arr3[1][1][2]
arr3[0][1][1:]

array([5, 6])

In [7]:
import numpy as np
# int, str, float, bool
# 정수, 실수  -> 문자
# 문자 -> 정수, 실수

str(np.array([2,3]))

'[2 3]'

In [8]:
arr_int = np.array([2,3])

In [9]:
arr_int.astype('str')

array(['2', '3'], dtype='<U11')

In [10]:
arr_int

array([2, 3])

In [11]:
arr_str =  arr_int.astype('str')

In [12]:
arr_str[0].dtype

dtype('<U1')

In [13]:
np.array(['1','2'])

array(['1', '2'], dtype='<U1')

In [14]:
arr_str

array(['2', '3'], dtype='<U11')

In [16]:
arr_str.astype('int')

array([2, 3])

In [17]:
arr_str.astype('int') +1 

array([3, 4])

In [18]:
arr_str.astype('float') +1 

array([3., 4.])