In [7]:
import numpy as np
# int, str, float, bool
# 정수, 실수  -> 문자
# 문자 -> 정수, 실수

str(np.array([2,3]))

'[2 3]'

In [8]:
arr_int = np.array([2,3])

In [9]:
arr_int.astype('str')

array(['2', '3'], dtype='<U11')

In [10]:
arr_int

array([2, 3])

In [11]:
arr_str =  arr_int.astype('str')

In [12]:
arr_str[0].dtype

dtype('<U1')

In [13]:
np.array(['1','2'])

array(['1', '2'], dtype='<U1')

In [14]:
arr_str

array(['2', '3'], dtype='<U11')

In [16]:
arr_str.astype('int')

array([2, 3])

In [17]:
arr_str.astype('int') +1 

array([3, 4])

In [18]:
arr_str.astype('float') +1 

array([3., 4.])