In [2]:
import numpy as np

# rank : 차원
a= np.array([1,2,3])
b=np.append(a, [4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
# axis 액시즈 : 축(중심)
# axis = 0 [행]
# axis = 1 [열]
help(np.append)


In [19]:
np.append(a, [7], axis=0) #차원이 맞다.
#np.append(a, [7], axis=1) #차원이 안맞어서, 2차원에서는 된다.
a_re = a.reshape(3, -1)
print(a_re.ndim)
# 차원을 맞춰야 실행 된다.
np.append(a_re, [[10],
                 [11],
                 [12]], axis = 1)

2


array([[ 1, 10],
       [ 2, 11],
       [ 3, 12]])

In [25]:
print(a.reshape(3,-1))
np.append(a.reshape(3,-1), [[11],[12],[13]],axis=1)

[[1]
 [2]
 [3]]


array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [43]:
x1 = np.arange(1, 20+1).reshape(4 , 5)
print(x1)
print(x1.ndim)
np.append(x1, [[1],[1],[1],[1]], axis=1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2


array([[ 1,  2,  3,  4,  5,  1],
       [ 6,  7,  8,  9, 10,  1],
       [11, 12, 13, 14, 15,  1],
       [16, 17, 18, 19, 20,  1]])