In [ ]:
# !pip install 패키지명

In [2]:
!pwd

/content


In [3]:
!find / -name 'numpy*'

/usr/include/boost/python/numpy
/usr/include/boost/python/numpy/numpy_object_mgr_traits.hpp
/usr/include/boost/python/numpy.hpp
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/include/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/_virtual_includes/pybind11/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy/numpyconfig.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tensorflow/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/dtensor/python/numpy_util.py
/usr/local/lib/python3.10/dist-packages/tensorflow/d

In [1]:
import numpy

In [1]:
import numpy as np

In [6]:
# help(np.array)

In [8]:
# np.array(1,2,3)

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [16]:
arr1=np.array([1,2,3])

In [4]:
type(arr1)

numpy.ndarray

In [17]:
arr1.shape

(3,)

In [18]:
arr1.size

3

In [19]:
arr1.ndim

1

In [10]:
arr2=np.array([[1,2,3], [4,5,6]])

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.size

6

In [14]:
arr2.ndim

2

In [20]:
arr3=np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [21]:
arr3.ndim

3

In [22]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
arr3.size

12

In [24]:
arr3.shape

(2, 2, 3)

In [25]:
arr=np.array([[1],
              [2],
              [-1.0],
              [3.14]])

In [26]:
arr

array([[ 1.  ],
       [ 2.  ],
       [-1.  ],
       [ 3.14]])

In [27]:
arr.shape

(4, 1)

In [28]:
arr.ndim

2

In [29]:
arr4=np.array([[[[1,2,-1.0,3.14]]]])

In [30]:
arr4

array([[[[ 1.  ,  2.  , -1.  ,  3.14]]]])

In [31]:
arr4.ndim

4

In [32]:
arr4.shape

(1, 1, 1, 4)

In [34]:
# 배열(넘파이 배열, np.array)  계산

In [37]:
mu=np.array([1,2,3])

In [36]:
nu=np.array([4,4,4])

In [39]:
mu + nu

array([5, 6, 7])

In [40]:
2* (mu + nu)

array([10, 12, 14])

In [41]:
# 행렬의 연산

In [42]:
A=np.array([[3,6], [4,5]])

In [43]:
A

array([[3, 6],
       [4, 5]])

In [44]:
B=np.array([[5,8], [6,7]])

In [45]:
A + B

array([[ 8, 14],
       [10, 12]])

In [46]:
A - B

array([[-2, -2],
       [-2, -2]])

In [50]:
D=np.array([[5,8,9], [6,7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [48]:
C=np.array([[5,8,9], [6,7,3]])

In [49]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [51]:
np.all([True,True,True])

True

In [52]:
np.all([True,True,False])

False

In [53]:
np.any([False,False,False])

False

In [54]:
np.any([True,False,False])

True