

(myenv1) C:\anaconda3\envs>python

>>> import tensorflow as tf
>>> tf.__version__
'2.10.0'
>>>


번역방법:
	1. 컴파일러 - 자바, c 전체를 먼저 해석해서 obejct(.class)파일을 만든다.
			문법적인 오류가 발생하면 에러를 모두 잡아야 실행이 가능하다.
			sematic error - 문법적 오류를 말한다. 있으면 실행불가
			syntax error - 논리적 오류, 문법적 오류는 없으나 잘못 짜서 결과가 안나온다. 훨씬 심각함.
			특징 - 사용할 변수와 함수를 모두 미리 정의를 해야 한다.
	2. 인터프리터 - 파이썬, javascript 
			한줄 읽고 해석해서 실행한다.
			변수나 함수가 미리 신언될 필요가 없다.
			필요하면 그때 그때 만들어서 사용한다. 코드가 길어지면 디버깅이 어렵다.


데이터 처리 - 
	SQL : sql기반 
		관계형 데이터베이스
		데이터를 테이블 구조로 저장한다.
		데이터 무결성, 일관성		
	

	NOSQL : json 객체로 저장한다. 
			object base -> javascript가 객체를 저장하는 방식
			mongodb
			비정형데이터
			빠르고, 검색 빠름.
			데이터 무결성 지원하지 않는다.
			보관해야할 중요 데이터 저장 못한다.

In [ ]:
# C:\ProgramData\anaconda3
# C:\ProgramData\anaconda3/Libary
# C:\ProgramData\anaconda3/Scripts

conda create --name myenv1
conda activate myenv1
conda install tensorflow

python
import tensorflow as tf
tf.__version__


conda install matplotlib
conda install seaborn




In [5]:
import numpy as np

In [6]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
[i for i in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [13]:
len10 = np.arange(10)

In [15]:
len(len10)

10

In [17]:
len10.size

10

In [19]:
np.array([111, 2.3, True])

array([111. ,   2.3,   1. ])

In [22]:
arr6 = np.array([111, 2.3, 'hi'])
arr6

array(['111', '2.3', 'hi'], dtype='<U32')

In [23]:
2**8

256

In [25]:
arr7 = np.array(['apple', 'banana', 'strawberry'])
arr7

array(['apple', 'banana', 'strawberry'], dtype='<U10')

In [27]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.linspace(-10, 10, 20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
li1 = [[1,2,3],[4,5,6],[7,8,9]]
li1[0][0]

1

In [34]:
np.array(li1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d = np.array(li1)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d.ndim

2

In [37]:
arr1d = np.array([1,3,5,7,9])
arr1d

array([1, 3, 5, 7, 9])

In [38]:
arr1d.ndim

1

In [41]:
arr3d = np.array([[[1,2], [3,4]], [[5,6] , [7,8]]])

In [42]:
arr3d[0][0][0]

1

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
arr2dZero = np.zeros((2,3))

In [45]:
arr2dZero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
arr2dZero2 = np.zeros((2,3), dtype='int64')
arr2dZero2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [47]:
type(arr2dZero2)

numpy.ndarray

In [50]:
a = [1,2,3]
b = [4,5,6]
c = a + b
print(c)

[1, 2, 3, 4, 5, 6]


In [51]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])
c1 = a1 + b1
print(c1)

[5 7 9]


In [56]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])
c1 = a1 + b1
c2 = a1 * b1

print(c1)
print(c2)
print(type(a1))
print(c1[0])
print(c1[1])
print(c1[2])

[5 7 9]
[ 4 10 18]
<class 'numpy.ndarray'>
5
7
9


In [61]:
# 2차원 만들기
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
m3 = m1 + m2
print(m3)

print(m1.shape) # 행렬의 열과 행의 개수 정보
print(m1.dtype) # 저장된 데이터 타입

print(m1[0, 0])
print(m1[0, 1])
print(m1[1, 0])
print(m1[1, 1])

for i in range(0, 2):
    for j in range(0, 2):
        print(m1[i,j], ',', end='')
    print()

[[ 6  8]
 [10 12]]
(2, 2)
int32
1
2
3
4
1 ,2 ,
3 ,4 ,


In [68]:
np.arange(0, 9)
# 요소의 값이 1씩 증가하는 배열을 만든다.
# 마지막 값은 빼고 생성 0부터 8까지

np.arange(1, 11, 2), np.arange(2, 11, 2)

(array([1, 3, 5, 7, 9]), array([ 2,  4,  6,  8, 10]))

In [69]:
a = np.array([123])
b = a # 얕은 복사를 한다.

a[1] = 10
print(a, b)
# 둘의 내용이 같다.


