In [2]:
import numpy as np

In [2]:
arr_2d = np.arange(1, 6+1)

In [3]:
arr_2d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr_2d = arr_2d.reshape(2,3)

In [7]:
arr_2d = np.delete(arr_2d, 4)

In [55]:
arr_2d = np.arange(1 , 6+1)
arr_2d = arr_2d.reshape(2,3)

In [56]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr_2d = np.delete(arr_2d, [1,4]) 

In [58]:
arr_2d

array([1, 3, 4, 6])

In [69]:
arr_2d = np.arange(1 , 6+1)
arr_2d = arr_2d.reshape(2,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr_2d = np.delete(arr_2d , 1, axis = 1)

In [71]:
arr_2d

array([[1, 3],
       [4, 6]])

In [72]:
arr_2d = np.append(arr_2d, [[7, 8]], axis= 0)
arr_2d

array([[1, 3],
       [4, 6],
       [7, 8]])

In [77]:
arr_2d= np.append(arr_2d, [[2],[4],[6]], axis=1)

In [78]:
arr_2d

array([[1, 3, 2],
       [4, 6, 4],
       [7, 8, 6]])

In [79]:
# 잘해야한다. -> numpy, 수학, 통계, 파이썬
arr_2d = np.delete(arr_2d, 1, axis =0 )

In [80]:
arr_2d

array([[1, 3, 2],
       [7, 8, 6]])

In [81]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# 각각의 원소끼리 연산하기
# 컴프리헨션 쓰면 안된다. for문이나
arr1 + arr2

array([5, 7, 9])

In [83]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
3
(3,)


In [85]:
# broadcasting 연산
np.array([1,2,3]) + 1

array([2, 3, 4])

In [86]:
np.array([1,2,3]) + np.array([[1,2,3]])

array([[3, 6, 9]])

In [87]:
np.array([1,2,3]) + np.array([[1,2,3],
                              [1,2,3]
                              ])

array([[2, 4, 6],
       [2, 4, 6]])

In [88]:
np.array([[1,2,3],
          [1,2,3]
        ]) + 1

array([[2, 3, 4],
       [2, 3, 4]])

In [89]:
#열이 안맞아서 오류난다. 2열 + 3열
np.array([1,2]) + np.array([[1,2,3],
                            [1,2,3]])

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [91]:
arr2 = np.arange(1, 6+1)
arr2 = arr2.reshape(2,3)    

In [92]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

2
6
(2, 3)


In [96]:
b = np.array([1,2,3])

In [97]:
b

array([1, 2, 3])

In [102]:
x= np.repeat(b, 1)
y= np.repeat(b, 2)
print(x)
print(y)

[1 2 3]
[1 1 2 2 3 3]


In [103]:
np.repeat(b, 10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [104]:
np.repeat(b, 10).reshape(3, 10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [105]:
b

array([1, 2, 3])

In [108]:
np.tile(b, 2)

array([1, 2, 3, 1, 2, 3])

In [109]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.tile(B, 2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [111]:
np.tile(B, 5)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [112]:
arr1 = np.array([1,2,3])

In [113]:
arr1 > 2

array([False, False,  True])

In [114]:
# 조건에 맞는 애들만 추려라.
# 불리언 인덱싱
arr1[arr1 > 2]

array([3])

In [116]:
# help(np.ufunc)

In [4]:
# cos 
np.cos(np.pi)

-1.0

In [6]:
np.cos(np.pi/2)

6.123233995736766e-17

In [8]:
print(f"{6.123233995736766e-17:.2f}")

0.00


In [13]:
arr1 = np.arange(1, 10 +1)

In [14]:
np.sum(arr1)

55

In [16]:
np.mean(arr1)

5.5

In [17]:
np.median(arr1)

5.5

In [19]:
stu_height = np.array([166,168,170,172,174])

In [24]:
# 표준편차 구하세요...(하나하나 계산해서, 함수)
np.std(stu_height) 

2.8284271247461903

In [51]:
# 표준편차를 구하세요
x_bar = np.mean(stu_height)
s_power = sum ((stu_height - x_bar)**2) / (len(stu_height)-1)
np.sqrt(s_power) # 표본표준편차

3.1622776601683795

In [38]:
np.sqrt(np.mean((abs(stu_height- np.mean(stu_height)))**2))

2.8284271247461903

In [ ]:
print(f"{6.123233995736766e-17:.2f}")

0.00


In [39]:
np.var(stu_height)
# 통계 제대로 하려면 R 쓰거나, 통계 라이브러리 설치 해야 된다.

8.0

In [45]:
import statistics as st 

# 표본 표준편차
st.variance(stu_height)
# 모 표준편차
st.pstdev(stu_height)  
st.pstdev(stu_height.astype('float'))  



2.8284271247461903

In [52]:
sung  = np.array(['남','여','남','여','남', '여'])

In [53]:
np.unique(sung)

array(['남', '여'], dtype='<U1')

In [62]:
# 행렬은 대문자로.
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [56]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [57]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [65]:
# 역행렬
A = np.array([1,2,3,4]).reshape(2,2)
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
A_inv = np.linalg.inv(A)

In [68]:
I = np.dot(A, A_inv)

In [70]:
np.round(I, 2)

array([[1., 0.],
       [0., 1.]])

In [71]:
np.linalg.det(A)

-2.0000000000000004

In [72]:
np.round(np.linalg.det(A))

-2.0