In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
import pandas as pd

In [5]:
df_ori = pd.read_csv('./data/sonar3.csv',header=None)
df = df_ori

In [6]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   0  
1  0.0052  0.0044   0  
2  0.0095  0.0078   0  
3  0.0040  0.0117   0  
4  0.0107  0.0094   0  

[5 rows x 61 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [8]:
df[60].value_counts()

60
1    111
0     97
Name: count, dtype: int64

In [9]:
X = df.iloc[:, :60].values
y = df.iloc[:, 60].values

In [10]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# 기본값 훈련셋, 테스트셋
# train_test_split ---> HoldOut 
# 0.75 : 0.25 비율이 기본값이다. (*100 퍼센트)
# 섞여서 나온다.

In [14]:
train_test_split(X, y, test_size=0.3, shuffle=True)

[array([[0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115],
        [0.0139, 0.0222, 0.0089, ..., 0.0059, 0.0039, 0.0048],
        [0.0721, 0.1574, 0.1112, ..., 0.0147, 0.0157, 0.0129],
        ...,
        [0.0317, 0.0956, 0.1321, ..., 0.0143, 0.0036, 0.0103],
        [0.0712, 0.0901, 0.1276, ..., 0.0101, 0.0095, 0.0068],
        [0.0164, 0.0173, 0.0347, ..., 0.0035, 0.0056, 0.004 ]]),
 array([[0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006 ],
        [0.0125, 0.0152, 0.0218, ..., 0.0041, 0.0086, 0.0058],
        [0.0228, 0.0853, 0.1   , ..., 0.0093, 0.0012, 0.0036],
        ...,
        [0.0025, 0.0309, 0.0171, ..., 0.0016, 0.0028, 0.0014],
        [0.0116, 0.0744, 0.0367, ..., 0.0044, 0.0057, 0.0035],
        [0.0225, 0.0019, 0.0075, ..., 0.0035, 0.0021, 0.0027]]),
 array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0

In [15]:
208* 0.7

145.6

In [16]:
X_train , X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3, shuffle=True)

In [17]:
X_train.shape

(145, 60)

In [18]:
X_test.shape

(63, 60)

In [19]:
y_train.shape

(145,)

In [20]:
y_test.shape

(63,)

In [21]:
# 학습용, 테스트용
# X_train , X_test, 
# y_train , y_test

In [31]:
model = Sequential()
model.add( Dense(36, 
                input_dim=60,
                activation='relu'
))
model.add( Dense(18, activation='relu'))
model.add( Dense(1, activation='sigmoid'))

model.compile( 
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit( X_train, y_train,
                    epochs=200, batch_size=10 )

Epoch 1/200
15/15 [==============================] - 1s 1ms/step - loss: 0.7023 - accuracy: 0.4897
Epoch 2/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6725 - accuracy: 0.6000
Epoch 3/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6665 - accuracy: 0.5517
Epoch 4/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6569 - accuracy: 0.5517
Epoch 5/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6531 - accuracy: 0.6000
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6420 - accuracy: 0.5724
Epoch 7/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6294 - accuracy: 0.6207
Epoch 8/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6149 - accuracy: 0.7310
Epoch 9/200
15/15 [==============================] - 0s 1ms/step - loss: 0.6011 - accuracy: 0.6690
Epoch 10/200
15/15 [==============================] - 0s 1ms/step - loss: 0.5859 - accuracy: 0.7655
Epoch 11/

In [22]:
model = Sequential()
model.add( Dense(24, 
                input_dim=60,
                activation='relu'
))
model.add( Dense(10, activation='relu'))
model.add( Dense(1, activation='sigmoid'))

model.compile( 
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit( X_test, y_test,
                    epochs=200, batch_size=10 )

Epoch 1/200
7/7 [==============================] - 1s 2ms/step - loss: 0.7155 - accuracy: 0.4127
Epoch 2/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6891 - accuracy: 0.5238
Epoch 3/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6710 - accuracy: 0.6349
Epoch 4/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6649 - accuracy: 0.6667
Epoch 5/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6592 - accuracy: 0.6667
Epoch 6/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6550 - accuracy: 0.6825
Epoch 7/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6491 - accuracy: 0.6667
Epoch 8/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6448 - accuracy: 0.6984
Epoch 9/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6407 - accuracy: 0.6984
Epoch 10/200
7/7 [==============================] - 0s 1ms/step - loss: 0.6364 - accuracy: 0.6825
Epoch 11/200
7/7 [===========

In [23]:
# 실제 모델 정확도는?? 테스트용으로 확인 해라. 
# model.evaluate( x=None,  
#     y=None,  
#     batch_size=None,  
#     verbose='auto',  
#     sample_weight=None,  
#     steps=None,  
#     callbacks=None,  
#     max_queue_size=10,  
#     workers=1,  
#     use_multiprocessing=False,  
#     return_dict=False,  
#     **kwargs,  )
model.evaluate( X_test, y_test )

2/2 [==============================] - 0s 2ms/step - loss: 0.0749 - accuracy: 1.0000


[0.07493709772825241, 1.0]

In [24]:
score = model.evaluate( X_test, y_test )

2/2 [==============================] - 0s 3ms/step - loss: 0.0749 - accuracy: 1.0000


In [25]:
score

[0.07493709772825241, 1.0]

In [26]:
score[1]

1.0

In [ ]:
# test셋에서의 정확도를 가지고 판단해야 한다. 100% 정확도를 얻음
